import type {
  ComponentDefinition,
  DashboardConfig,
  DataSource,
  Dataset,
  JobRun,
} from './platform-types';

const cicdProjects = ['Vortex Core', 'Vehicle OS', 'Cockpit'];
const cicdEnvironments = ['生产', '预发', '开发'];
const cicdDates = [
  ...Array.from({ length: 17 }, (_, index) => `08.${index + 15}`),
  ...Array.from(
    { length: 13 },
    (_, index) => `09.${String(index + 1).padStart(2, '0')}`,
  ),
];

const cicdDailyRows = cicdDates.flatMap((date, dateIndex) =>
  cicdProjects.flatMap((project, projectIndex) =>
    cicdEnvironments.map((environment, environmentIndex) => {
      const pipelines =
        17 +
        ((dateIndex * 5 + projectIndex * 3 + environmentIndex * 2) % 15) +
        projectIndex * 3;
      const failed = Math.max(
        1,
        Math.round(
          pipelines *
            (0.035 +
              ((dateIndex + projectIndex + environmentIndex) % 4) * 0.009),
        ),
      );
      return {
        date,
        project,
        environment,
        pipelines,
        succeeded: pipelines - failed,
        failed,
        recovered: Math.max(0, failed - ((dateIndex + projectIndex) % 2)),
        avgDuration:
          328 +
          projectIndex * 34 +
          environmentIndex * 18 +
          (dateIndex % 6) * 11,
      };
    }),
  ),
);

const cicdTriggerRows = cicdDates.flatMap((date, dateIndex) =>
  cicdProjects.flatMap((project, projectIndex) =>
    cicdEnvironments.flatMap((environment, environmentIndex) =>
      [
        {
          trigger: '代码推送',
          runs: 8 + ((dateIndex + projectIndex * 2 + environmentIndex) % 7),
        },
        {
          trigger: '合并请求',
          runs: 5 + ((dateIndex * 2 + projectIndex + environmentIndex) % 6),
        },
        {
          trigger: '定时任务',
          runs: 3 + ((dateIndex + projectIndex + environmentIndex * 2) % 4),
        },
        {
          trigger: '手动执行',
          runs: 2 + ((dateIndex + projectIndex * 3 + environmentIndex) % 3),
        },
      ].map((item) => ({ date, project, environment, ...item })),
    ),
  ),
);

export const datasets: Dataset[] = [
  {
    id: 'cicd_delivery_daily',
    name: 'CI/CD 交付日报',
    description: '按项目、环境和日期聚合的流水线执行与恢复数据。',
    version: 'v1',
    owner: '平台基础组',
    source: 'gitlab_commits',
    updatedAt: '今天 16:42',
    refresh: '每 1 分钟',
    cacheTtl: '30 秒',
    permission: '研发组织',
    fields: [
      {
        key: 'date',
        label: '日期',
        type: 'datetime',
        role: 'time',
        description: '统计日期，MM.DD',
      },
      {
        key: 'project',
        label: '项目',
        type: 'string',
        role: 'dimension',
        description: '流水线所属项目',
      },
      {
        key: 'environment',
        label: '环境',
        type: 'string',
        role: 'dimension',
        description: '目标部署环境',
      },
      {
        key: 'pipelines',
        label: '流水线数',
        type: 'number',
        role: 'metric',
        description: '流水线执行总数',
      },
      {
        key: 'succeeded',
        label: '成功数',
        type: 'number',
        role: 'metric',
        description: '成功结束的流水线数',
      },
      {
        key: 'failed',
        label: '失败数',
        type: 'number',
        role: 'metric',
        description: '失败结束的流水线数',
      },
      {
        key: 'recovered',
        label: '已恢复',
        type: 'number',
        role: 'metric',
        description: '重试或修复后恢复的流水线数',
      },
      {
        key: 'avgDuration',
        label: '平均耗时',
        type: 'number',
        role: 'metric',
        description: '平均执行耗时，单位秒',
      },
    ],
    rows: cicdDailyRows,
    lineage: [
      'GitLab Webhook',
      'Pipeline Collector',
      'SQL Aggregate',
      'cicd_delivery_daily',
    ],
  },
  {
    id: 'cicd_trigger_distribution',
    name: 'CI/CD 触发方式分布',
    description: '按项目和环境聚合的流水线触发来源。',
    version: 'v1',
    owner: '平台基础组',
    source: 'gitlab_commits',
    updatedAt: '今天 16:42',
    refresh: '每 5 分钟',
    cacheTtl: '1 分钟',
    permission: '研发组织',
    fields: [
      {
        key: 'date',
        label: '日期',
        type: 'datetime',
        role: 'time',
        description: '统计日期，MM.DD',
      },
      {
        key: 'project',
        label: '项目',
        type: 'string',
        role: 'dimension',
        description: '流水线所属项目',
      },
      {
        key: 'environment',
        label: '环境',
        type: 'string',
        role: 'dimension',
        description: '目标部署环境',
      },
      {
        key: 'trigger',
        label: '触发方式',
        type: 'string',
        role: 'dimension',
        description: '流水线启动来源',
      },
      {
        key: 'runs',
        label: '执行次数',
        type: 'number',
        role: 'metric',
        description: '触发方式对应的执行次数',
      },
    ],
    rows: cicdTriggerRows,
    lineage: [
      'GitLab Webhook',
      'Trigger Classifier',
      'cicd_trigger_distribution',
    ],
  },
  {
    id: 'cicd_recent_runs',
    name: 'CI/CD 最近运行',
    description: '最近的流水线运行状态、分支和触发信息。',
    version: 'v1',
    owner: '平台基础组',
    source: 'gitlab_commits',
    updatedAt: '今天 16:42',
    refresh: '每 30 秒',
    cacheTtl: '15 秒',
    permission: '研发组织',
    fields: [
      {
        key: 'pipelineId',
        label: '流水线',
        type: 'string',
        role: 'dimension',
        description: '流水线运行 ID',
      },
      {
        key: 'project',
        label: '项目',
        type: 'string',
        role: 'dimension',
        description: '流水线所属项目',
      },
      {
        key: 'branch',
        label: '分支',
        type: 'string',
        role: 'dimension',
        description: '触发分支',
      },
      {
        key: 'environment',
        label: '环境',
        type: 'string',
        role: 'dimension',
        description: '目标部署环境',
      },
      {
        key: 'trigger',
        label: '触发方式',
        type: 'string',
        role: 'dimension',
        description: '流水线启动来源',
      },
      {
        key: 'actor',
        label: '触发人',
        type: 'string',
        role: 'dimension',
        description: '流水线触发用户',
      },
      {
        key: 'status',
        label: '状态',
        type: 'string',
        role: 'dimension',
        description: '当前运行状态',
      },
      {
        key: 'duration',
        label: '耗时',
        type: 'number',
        role: 'metric',
        description: '流水线运行耗时，单位秒',
      },
      {
        key: 'startedAt',
        label: '开始时间',
        type: 'datetime',
        role: 'time',
        description: '流水线开始时间',
      },
    ],
    rows: [
      {
        pipelineId: '#18427',
        project: 'Vortex Core',
        branch: 'release/3.8',
        environment: '生产',
        trigger: '合并请求',
        actor: '陈思远',
        status: '成功',
        duration: 376,
        startedAt: '16:38',
      },
      {
        pipelineId: '#18426',
        project: 'Vehicle OS',
        branch: 'main',
        environment: '预发',
        trigger: '代码推送',
        actor: '王子涵',
        status: '运行中',
        duration: 248,
        startedAt: '16:34',
      },
      {
        pipelineId: '#18425',
        project: 'Cockpit',
        branch: 'feature/audio',
        environment: '开发',
        trigger: '代码推送',
        actor: '李明',
        status: '失败',
        duration: 192,
        startedAt: '16:29',
      },
      {
        pipelineId: '#18424',
        project: 'Vortex Core',
        branch: 'main',
        environment: '预发',
        trigger: '定时任务',
        actor: '系统',
        status: '成功',
        duration: 421,
        startedAt: '16:22',
      },
      {
        pipelineId: '#18423',
        project: 'Vehicle OS',
        branch: 'hotfix/can',
        environment: '生产',
        trigger: '手动执行',
        actor: '张晨',
        status: '成功',
        duration: 354,
        startedAt: '16:16',
      },
      {
        pipelineId: '#18422',
        project: 'Cockpit',
        branch: 'main',
        environment: '生产',
        trigger: '合并请求',
        actor: '赵雨桐',
        status: '成功',
        duration: 405,
        startedAt: '16:09',
      },
      {
        pipelineId: '#18421',
        project: 'Vortex Core',
        branch: 'feature/cache',
        environment: '开发',
        trigger: '代码推送',
        actor: '陈思远',
        status: '已取消',
        duration: 86,
        startedAt: '15:58',
      },
      {
        pipelineId: '#18420',
        project: 'Vehicle OS',
        branch: 'main',
        environment: '开发',
        trigger: '定时任务',
        actor: '系统',
        status: '成功',
        duration: 338,
        startedAt: '15:47',
      },
    ],
    lineage: ['GitLab Pipeline API', 'HTTP Connector', 'cicd_recent_runs'],
  },
  {
    id: 'tool_usage_daily',
    name: '工具使用日报',
    description: '内部研发工具的注册、调用、Token 与采用率快照。',
    version: 'v3',
    owner: '研发效能组',
    source: 'vortex_usage_api',
    updatedAt: '今天 14:30',
    refresh: '每 10 分钟',
    cacheTtl: '5 分钟',
    permission: '研发组织',
    fields: [
      {
        key: 'tool',
        label: '工具',
        type: 'string',
        role: 'dimension',
        description: '工具显示名称',
      },
      {
        key: 'registered',
        label: '注册用户',
        type: 'number',
        role: 'metric',
        description: '累计注册人数',
      },
      {
        key: 'active',
        label: '活跃用户',
        type: 'number',
        role: 'metric',
        description: '当日去重活跃人数',
      },
      {
        key: 'calls',
        label: '调用次数',
        type: 'number',
        role: 'metric',
        description: '当日工具调用总数',
      },
      {
        key: 'tokens',
        label: 'Token 消耗',
        type: 'number',
        role: 'metric',
        description: '输入与输出 Token 合计',
      },
      {
        key: 'adoption',
        label: '采用率',
        type: 'number',
        role: 'metric',
        description: '活跃用户 / 注册用户',
      },
      {
        key: 'updatedAt',
        label: '更新时间',
        type: 'datetime',
        role: 'time',
        description: '数据快照时间',
      },
    ],
    rows: [
      {
        tool: 'DevPilot',
        registered: 876,
        active: 542,
        calls: 2140,
        tokens: 1420000,
        adoption: 61.9,
        updatedAt: '2026-09-09T14:30:00+08:00',
      },
      {
        tool: 'Code Review',
        registered: 624,
        active: 316,
        calls: 860,
        tokens: 680000,
        adoption: 50.6,
        updatedAt: '2026-09-09T14:30:00+08:00',
      },
      {
        tool: 'ARXML Studio',
        registered: 318,
        active: 205,
        calls: 425,
        tokens: 260000,
        adoption: 64.5,
        updatedAt: '2026-09-09T14:30:00+08:00',
      },
      {
        tool: 'LogLens',
        registered: 246,
        active: 121,
        calls: 310,
        tokens: 310000,
        adoption: 49.2,
        updatedAt: '2026-09-09T14:30:00+08:00',
      },
      {
        tool: 'TestCraft',
        registered: 192,
        active: 86,
        calls: 165,
        tokens: 140000,
        adoption: 44.8,
        updatedAt: '2026-09-09T14:30:00+08:00',
      },
      {
        tool: 'DocFlow',
        registered: 108,
        active: 42,
        calls: 60,
        tokens: 30000,
        adoption: 38.9,
        updatedAt: '2026-09-09T14:30:00+08:00',
      },
    ],
    lineage: [
      'Vortex Usage API',
      'HTTP Connector',
      'JS Normalize',
      'tool_usage_daily',
    ],
  },
  {
    id: 'test_case_status',
    name: 'CICT 测试进度',
    description: '按项目聚合的 Case 执行与解析结果。',
    version: 'v5',
    owner: '测试平台组',
    source: 'cict_agent_output',
    updatedAt: '今天 14:32',
    refresh: 'Webhook 实时',
    cacheTtl: '30 秒',
    permission: '项目成员',
    fields: [
      {
        key: 'project',
        label: '项目',
        type: 'string',
        role: 'dimension',
        description: '车型或产品项目',
      },
      {
        key: 'platform',
        label: '平台',
        type: 'string',
        role: 'dimension',
        description: '测试运行平台',
      },
      {
        key: 'owner',
        label: '负责人',
        type: 'string',
        role: 'dimension',
        description: '任务提交或维护人员',
      },
      {
        key: 'total',
        label: 'Case 总数',
        type: 'number',
        role: 'metric',
        description: '当日新增测试用例数',
      },
      {
        key: 'passed',
        label: '通过数',
        type: 'number',
        role: 'metric',
        description: '测试成功 Case 数',
      },
      {
        key: 'failed',
        label: '失败数',
        type: 'number',
        role: 'metric',
        description: '测试失败 Case 数',
      },
      {
        key: 'passRate',
        label: '通过率',
        type: 'number',
        role: 'metric',
        description: '通过数 / 总数',
      },
      {
        key: 'status',
        label: '解析状态',
        type: 'string',
        role: 'dimension',
        description: 'Agent 解析任务状态',
      },
      {
        key: 'updatedAt',
        label: '更新时间',
        type: 'datetime',
        role: 'time',
        description: '最近一次结果时间',
      },
    ],
    rows: [
      {
        project: 'BYD',
        platform: 'Linux x86_64',
        owner: '陈思远',
        total: 326,
        passed: 301,
        failed: 25,
        passRate: 92.3,
        status: '已完成',
        updatedAt: '2026-09-09T14:32:00+08:00',
      },
      {
        project: 'Project N',
        platform: 'QNX ARM64',
        owner: '王子涵',
        total: 248,
        passed: 239,
        failed: 9,
        passRate: 96.4,
        status: '已完成',
        updatedAt: '2026-09-09T14:28:00+08:00',
      },
      {
        project: 'Platform X',
        platform: 'Windows x64',
        owner: '李明',
        total: 186,
        passed: 182,
        failed: 4,
        passRate: 97.8,
        status: '解析中',
        updatedAt: '2026-09-09T14:18:00+08:00',
      },
      {
        project: 'E/E Core',
        platform: 'QNX ARM64',
        owner: '张晨',
        total: 142,
        passed: 137,
        failed: 5,
        passRate: 96.5,
        status: '已完成',
        updatedAt: '2026-09-09T14:11:00+08:00',
      },
      {
        project: 'Gateway',
        platform: 'Linux x86_64',
        owner: '赵雨桐',
        total: 96,
        passed: 88,
        failed: 8,
        passRate: 91.7,
        status: '待处理',
        updatedAt: '2026-09-09T14:04:00+08:00',
      },
    ],
    lineage: [
      'CICT Result',
      'Webhook Connector',
      'Python Report Parser',
      'Agent Enrichment',
      'test_case_status',
    ],
  },
  {
    id: 'pipeline_runs',
    name: '解析流水线运行',
    description: 'Go Worker、ACP 会话与 Agent 任务的运行快照。',
    version: 'v2',
    owner: '平台基础组',
    source: 'cict_agent_output',
    updatedAt: '今天 14:32',
    refresh: '每 30 秒',
    cacheTtl: '15 秒',
    permission: '平台管理员',
    fields: [
      {
        key: 'stage',
        label: '阶段',
        type: 'string',
        role: 'dimension',
        description: '流水线处理阶段',
      },
      {
        key: 'running',
        label: '运行中',
        type: 'number',
        role: 'metric',
        description: '当前运行任务数',
      },
      {
        key: 'queued',
        label: '排队中',
        type: 'number',
        role: 'metric',
        description: '等待任务数',
      },
      {
        key: 'completed',
        label: '已完成',
        type: 'number',
        role: 'metric',
        description: '今日完成任务数',
      },
      {
        key: 'duration',
        label: '平均耗时',
        type: 'number',
        role: 'metric',
        description: '平均处理时间，单位秒',
      },
      {
        key: 'status',
        label: '状态',
        type: 'string',
        role: 'dimension',
        description: '阶段健康状态',
      },
    ],
    rows: [
      {
        stage: '结果入队',
        running: 0,
        queued: 12,
        completed: 1120,
        duration: 1.2,
        status: '正常',
      },
      {
        stage: 'Go 调度',
        running: 8,
        queued: 4,
        completed: 1108,
        duration: 2.8,
        status: '正常',
      },
      {
        stage: 'ACP 会话',
        running: 8,
        queued: 0,
        completed: 1100,
        duration: 8.4,
        status: '正常',
      },
      {
        stage: 'Agent 分析',
        running: 8,
        queued: 0,
        completed: 1092,
        duration: 31.6,
        status: '关注',
      },
      {
        stage: '结果归档',
        running: 2,
        queued: 0,
        completed: 1090,
        duration: 4.2,
        status: '正常',
      },
    ],
    lineage: [
      'CICT Queue',
      'Go Scheduler',
      'ACP Protocol',
      'Agent CLI',
      'pipeline_runs',
    ],
  },
  {
    id: 'source_health',
    name: '数据源健康度',
    description: '所有连接器最近采集状态与成功率。',
    version: 'v1',
    owner: '数据平台组',
    source: 'platform_runtime',
    updatedAt: '今天 14:32',
    refresh: '每 1 分钟',
    cacheTtl: '30 秒',
    permission: '平台管理员',
    fields: [
      {
        key: 'source',
        label: '数据源',
        type: 'string',
        role: 'dimension',
        description: '数据源显示名称',
      },
      {
        key: 'connector',
        label: '连接器',
        type: 'string',
        role: 'dimension',
        description: '连接器类型',
      },
      {
        key: 'status',
        label: '状态',
        type: 'string',
        role: 'dimension',
        description: '最近采集状态',
      },
      {
        key: 'successRate',
        label: '成功率',
        type: 'number',
        role: 'metric',
        description: '近 24 小时成功率',
      },
      {
        key: 'latency',
        label: '延迟',
        type: 'number',
        role: 'metric',
        description: '最近采集延迟，单位毫秒',
      },
      {
        key: 'lastRun',
        label: '最近运行',
        type: 'datetime',
        role: 'time',
        description: '最近调度时间',
      },
    ],
    rows: [
      {
        source: 'Vortex Usage',
        connector: 'HTTP API',
        status: '健康',
        successRate: 99.8,
        latency: 218,
        lastRun: '14:30',
      },
      {
        source: 'CICT Agent Output',
        connector: 'Webhook',
        status: '健康',
        successRate: 99.4,
        latency: 86,
        lastRun: '14:32',
      },
      {
        source: 'Jira Test Issues',
        connector: 'Jira',
        status: '健康',
        successRate: 98.7,
        latency: 452,
        lastRun: '14:20',
      },
      {
        source: 'Feishu Specs',
        connector: 'Feishu',
        status: '关注',
        successRate: 94.2,
        latency: 1260,
        lastRun: '14:10',
      },
      {
        source: 'GitLab Commits',
        connector: 'GitLab',
        status: '健康',
        successRate: 99.9,
        latency: 304,
        lastRun: '14:25',
      },
    ],
    lineage: ['Connector Runtime', 'Run Metrics', 'source_health'],
  },
];

export const initialSources: DataSource[] = [
  {
    id: 'vortex_usage_api',
    name: 'Vortex Usage',
    connector: 'http',
    endpoint: 'https://usage.internal/api/v2/metrics',
    schedule: '*/10 * * * *',
    outputDataset: 'tool_usage_daily',
    authRef: 'vortex-prod-token',
    owner: '研发效能组',
    status: 'healthy',
    lastRun: '2 分钟前',
    successRate: 99.8,
  },
  {
    id: 'cict_agent_output',
    name: 'CICT Agent Output',
    connector: 'webhook',
    endpoint: '/hooks/cict/result',
    schedule: '实时',
    outputDataset: 'test_case_status',
    authRef: 'cict-webhook-secret',
    owner: '测试平台组',
    status: 'healthy',
    lastRun: '刚刚',
    successRate: 99.4,
  },
  {
    id: 'jira_test_issues',
    name: 'Jira Test Issues',
    connector: 'jira',
    endpoint: 'jira.internal/rest/api/3/search',
    schedule: '*/10 * * * *',
    outputDataset: 'jira_test_cases',
    authRef: 'jira-prod-token',
    owner: '测试平台组',
    status: 'healthy',
    lastRun: '12 分钟前',
    successRate: 98.7,
  },
  {
    id: 'feishu_specs',
    name: 'Feishu Specs',
    connector: 'feishu',
    endpoint: 'bitable/appbCICT/specs',
    schedule: '*/15 * * * *',
    outputDataset: 'requirement_specs',
    authRef: 'feishu-app-credential',
    owner: '产品工程组',
    status: 'warning',
    lastRun: '22 分钟前',
    successRate: 94.2,
  },
  {
    id: 'gitlab_commits',
    name: 'GitLab Commits',
    connector: 'gitlab',
    endpoint: 'gitlab.internal/api/v4/projects',
    schedule: '*/5 * * * *',
    outputDataset: 'code_commits',
    authRef: 'gitlab-read-token',
    owner: '平台基础组',
    status: 'healthy',
    lastRun: '7 分钟前',
    successRate: 99.9,
  },
  {
    id: 'manual_excel',
    name: '季度工具登记表',
    connector: 'file',
    endpoint: 'R2://imports/tool-register.xlsx',
    schedule: '手动上传',
    outputDataset: 'tool_registration',
    owner: '研发效能组',
    status: 'disabled',
    lastRun: '9 月 1 日',
    successRate: 100,
  },
];

export const componentDefinitions: ComponentDefinition[] = [
  {
    type: 'metric',
    name: '指标卡',
    description: '聚合显示单个数值',
    roles: { value: ['number'] },
    supports: ['聚合', '筛选', '刷新'],
    status: 'stable',
  },
  {
    type: 'barChart',
    name: '柱状图',
    description: '比较分类指标',
    roles: {
      category: ['string', 'datetime'],
      value: ['number'],
      series: ['string'],
    },
    supports: ['筛选', '下钻', '刷新'],
    status: 'stable',
  },
  {
    type: 'lineChart',
    name: '折线图',
    description: '展示时间或序列趋势',
    roles: {
      category: ['string', 'datetime'],
      value: ['number'],
      series: ['string'],
    },
    supports: ['筛选', '缩放', '刷新'],
    status: 'stable',
  },
  {
    type: 'pieChart',
    name: '环形图',
    description: '展示分类占比',
    roles: { category: ['string'], value: ['number'] },
    supports: ['筛选', '下钻'],
    status: 'stable',
  },
  {
    type: 'table',
    name: '数据表格',
    description: '展示明细与多字段结果',
    roles: {},
    supports: ['筛选', '排序', '分页', '导出'],
    status: 'stable',
  },
  {
    type: 'progress',
    name: '进度卡',
    description: '展示百分比或完成度',
    roles: { category: ['string'], value: ['number'] },
    supports: ['筛选', '刷新'],
    status: 'stable',
  },
  {
    type: 'statusList',
    name: '状态列表',
    description: '展示服务或任务状态',
    roles: { category: ['string'], series: ['string'] },
    supports: ['筛选', '刷新'],
    status: 'stable',
  },
  {
    type: 'markdown',
    name: '说明面板',
    description: '展示静态说明与链接',
    roles: {},
    supports: ['Markdown'],
    status: 'beta',
  },
];

export const initialDashboards: DashboardConfig[] = [
  {
    id: 'engineering-overview',
    title: '研发效能总览',
    description: '工具、测试与平台健康度的统一视图',
    status: 'published',
    updatedAt: '今天 14:30',
    layout: { columns: 24, rowHeight: 20, gap: 16 },
    widgets: [
      {
        id: 'tool-calls',
        component: 'metric',
        dataset: 'tool_usage_daily',
        title: '今日工具调用',
        position: { x: 0, y: 0, w: 6, h: 5 },
        mapping: { value: 'calls' },
        options: {
          aggregate: 'sum',
          unit: ' 次',
          description: '所有已接入工具',
        },
      },
      {
        id: 'active-users',
        component: 'metric',
        dataset: 'tool_usage_daily',
        title: '今日活跃用户',
        position: { x: 6, y: 0, w: 6, h: 5 },
        mapping: { value: 'active' },
        options: { aggregate: 'sum', unit: ' 人', description: '按工具统计' },
      },
      {
        id: 'test-cases',
        component: 'metric',
        dataset: 'test_case_status',
        title: '新增测试 Case',
        position: { x: 12, y: 0, w: 6, h: 5 },
        mapping: { value: 'total' },
        options: { aggregate: 'sum', unit: ' 个', description: '当天累计' },
      },
      {
        id: 'source-rate',
        component: 'metric',
        dataset: 'source_health',
        title: '数据源成功率',
        position: { x: 18, y: 0, w: 6, h: 5 },
        mapping: { value: 'successRate' },
        options: {
          aggregate: 'avg',
          unit: '%',
          precision: 1,
          description: '近 24 小时',
        },
      },
      {
        id: 'tool-rank',
        component: 'barChart',
        dataset: 'tool_usage_daily',
        title: '工具调用分布',
        position: { x: 0, y: 5, w: 14, h: 14 },
        mapping: { category: 'tool', value: 'calls' },
        options: { color: '#8da4d5' },
      },
      {
        id: 'source-list',
        component: 'statusList',
        dataset: 'source_health',
        title: '数据源状态',
        position: { x: 14, y: 5, w: 10, h: 14 },
        mapping: { category: 'source', series: 'status', value: 'successRate' },
        query: { limit: 5 },
      },
    ],
  },
  {
    id: 'cict-progress',
    title: 'CICT 测试进度',
    description: '项目 Case、通过率与失败分布',
    status: 'published',
    updatedAt: '今天 14:32',
    layout: { columns: 24, rowHeight: 20, gap: 16 },
    widgets: [
      {
        id: 'case-total',
        component: 'metric',
        dataset: 'test_case_status',
        title: 'Case 总数',
        position: { x: 0, y: 0, w: 6, h: 5 },
        mapping: { value: 'total' },
        options: { aggregate: 'sum', unit: ' 个' },
      },
      {
        id: 'case-passed',
        component: 'metric',
        dataset: 'test_case_status',
        title: '测试通过',
        position: { x: 6, y: 0, w: 6, h: 5 },
        mapping: { value: 'passed' },
        options: { aggregate: 'sum', unit: ' 个' },
      },
      {
        id: 'case-failed',
        component: 'metric',
        dataset: 'test_case_status',
        title: '失败 Case',
        position: { x: 12, y: 0, w: 6, h: 5 },
        mapping: { value: 'failed' },
        options: { aggregate: 'sum', unit: ' 个', color: '#c66565' },
      },
      {
        id: 'pass-rate',
        component: 'metric',
        dataset: 'test_case_status',
        title: '平均通过率',
        position: { x: 18, y: 0, w: 6, h: 5 },
        mapping: { value: 'passRate' },
        options: { aggregate: 'avg', unit: '%', precision: 1 },
      },
      {
        id: 'failed-by-project',
        component: 'barChart',
        dataset: 'test_case_status',
        title: '项目失败 Case',
        position: { x: 0, y: 5, w: 12, h: 14 },
        mapping: { category: 'project', value: 'failed' },
        options: { color: '#c97979' },
      },
      {
        id: 'case-detail',
        component: 'table',
        dataset: 'test_case_status',
        title: '项目测试明细',
        position: { x: 12, y: 5, w: 12, h: 14 },
        mapping: {
          columns: [
            'project',
            'platform',
            'total',
            'passed',
            'failed',
            'status',
          ],
        },
        query: { limit: 6 },
      },
    ],
  },
  {
    id: 'pipeline-operations',
    title: '解析流水线',
    description: 'Go → ACP → Agent CLI 运行监控',
    status: 'draft',
    updatedAt: '昨天 18:20',
    layout: { columns: 24, rowHeight: 20, gap: 16 },
    widgets: [
      {
        id: 'running',
        component: 'metric',
        dataset: 'pipeline_runs',
        title: '运行中任务',
        position: { x: 0, y: 0, w: 6, h: 5 },
        mapping: { value: 'running' },
        options: { aggregate: 'sum', unit: ' 个' },
      },
      {
        id: 'queue',
        component: 'metric',
        dataset: 'pipeline_runs',
        title: '队列等待',
        position: { x: 6, y: 0, w: 6, h: 5 },
        mapping: { value: 'queued' },
        options: { aggregate: 'sum', unit: ' 个' },
      },
      {
        id: 'duration',
        component: 'barChart',
        dataset: 'pipeline_runs',
        title: '各阶段平均耗时',
        position: { x: 0, y: 5, w: 14, h: 14 },
        mapping: { category: 'stage', value: 'duration' },
        options: { color: '#9788bd', unit: ' 秒' },
      },
      {
        id: 'stage-status',
        component: 'statusList',
        dataset: 'pipeline_runs',
        title: '阶段状态',
        position: { x: 14, y: 5, w: 10, h: 14 },
        mapping: { category: 'stage', series: 'status', value: 'running' },
      },
    ],
  },
];

export const jobRuns: JobRun[] = [
  {
    id: 'run_98FK2',
    source: 'CICT Agent Output',
    dataset: 'test_case_status',
    trigger: 'webhook',
    status: 'success',
    rows: 386,
    duration: '42.8s',
    startedAt: '14:32:08',
  },
  {
    id: 'run_98FJQ',
    source: 'Vortex Usage',
    dataset: 'tool_usage_daily',
    trigger: 'schedule',
    status: 'success',
    rows: 6,
    duration: '3.2s',
    startedAt: '14:30:00',
  },
  {
    id: 'run_98FHD',
    source: 'GitLab Commits',
    dataset: 'code_commits',
    trigger: 'schedule',
    status: 'running',
    rows: 0,
    duration: '18.4s',
    startedAt: '14:25:00',
  },
  {
    id: 'run_98F80',
    source: 'Jira Test Issues',
    dataset: 'jira_test_cases',
    trigger: 'schedule',
    status: 'success',
    rows: 128,
    duration: '8.9s',
    startedAt: '14:20:00',
  },
  {
    id: 'run_98F21',
    source: 'Feishu Specs',
    dataset: 'requirement_specs',
    trigger: 'schedule',
    status: 'failed',
    rows: 0,
    duration: '30.0s',
    startedAt: '14:10:00',
  },
];

export const connectorLabels: Record<string, string> = {
  http: 'HTTP API',
  mysql: 'MySQL',
  postgresql: 'PostgreSQL',
  jira: 'Jira',
  feishu: '飞书',
  gitlab: 'GitLab',
  file: 'CSV / Excel',
  webhook: 'Webhook',
  agent: 'Agent 输出',
  script: '自定义脚本',
};
